name: Testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      # Runs a single command using the runners shell
      - name: Force XCode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: running unit testing
        run: xcodebuild test -scheme gimpolitan-clean-submission-expert -workspace gimpolitan-clean-submission-expert.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
      - name: Testing iOS app
        run:
          xcodebuild -workspace gimpolitan-clean-submission-expert.xcworkspace \
          -scheme gimpolitan-clean-submission-expert\ iOS \
          -destination platform=iOS\ Simulator,OS=14.4,name=iPhone\ 12 \
          clean test | xcpretty
     
