name: Testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Force XCode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
